# Generated by Django 5.2.3 on 2025-06-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la lección')),
                ('lesson_type', models.CharField(choices=[('TEXT', 'Texto'), ('VIDEO', 'Video')], default='TEXT', max_length=10, verbose_name='Tipo de Lección')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Contenido de Texto')),
                ('video_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de Video (Vimeo/YouTube)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['order'],
            },
        ),
    ]
